FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /build/restaurant ./cmd/restaurant-service \
    && go clean -cache -modcache

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /build/restaurant .

CMD ["./restaurant"]