// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "kitchens/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RestaurantProvider is an autogenerated mock type for the RestaurantProvider type
type RestaurantProvider struct {
	mock.Mock
}

// GetMenu provides a mock function with given fields: ctx, restaurantID
func (_m *RestaurantProvider) GetMenu(ctx context.Context, restaurantID uuid.UUID) ([]domain.MenuItem, error) {
	ret := _m.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for GetMenu")
	}

	var r0 []domain.MenuItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.MenuItem, error)); ok {
		return rf(ctx, restaurantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.MenuItem); ok {
		r0 = rf(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MenuItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRestaurants provides a mock function with given fields: ctx
func (_m *RestaurantProvider) GetRestaurants(ctx context.Context) ([]domain.Restaurant, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRestaurants")
	}

	var r0 []domain.Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Restaurant, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Restaurant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRestaurantProvider creates a new instance of RestaurantProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestaurantProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestaurantProvider {
	mock := &RestaurantProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
