// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "kitchens/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RestaurantRepository is an autogenerated mock type for the RestaurantRepository type
type RestaurantRepository struct {
	mock.Mock
}

// GetMenuItemsByIDs provides a mock function with given fields: ctx, itemIDs
func (_m *RestaurantRepository) GetMenuItemsByIDs(ctx context.Context, itemIDs []uuid.UUID) ([]domain.MenuItem, error) {
	ret := _m.Called(ctx, itemIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetMenuItemsByIDs")
	}

	var r0 []domain.MenuItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]domain.MenuItem, error)); ok {
		return rf(ctx, itemIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []domain.MenuItem); ok {
		r0 = rf(ctx, itemIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MenuItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, itemIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRestaurantRepository creates a new instance of RestaurantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestaurantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestaurantRepository {
	mock := &RestaurantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
